############################################################################3
#
# SC Configuration
#

- name: Check Storage Controllers are listening
  wait_for: host="{{ hostvars[item][hostvars[item]['java_iface']]['ipv4']['address'] }}" port=8773 state=started
  with_items: "{{ groups.sc }}"
  tags:
  - configureStorage
  register: listening
  ignore_errors: True

- name: Configure SC block manager
  shell: source "{{ euca_admin_creds }}" ;
         euca-modify-property -p "{{ item['partition'] }}".storage.blockstoragemanager="{{ item['mode'] }}"
  with_items:
  - "{{ sc_clusters }}"
  tags:
  - configureStorage
  ignore_errors: yes
  when:
  - listening|success

- name: Configure the block manager properties
  shell: source "{{ euca_admin_creds_path }}"/eucarc ; euca-modify-property -p "{{ item.0['partition'] }}".storage."{{ item.1['name'] }}"="{{ item.1['value'] }}"
  with_subelements:
  - "{{ sc_clusters }}"
  - properties
  register: sc_register
  until: sc_register.stdout.find("was") != -1
  retries: 20
  delay: 5
  tags:
  - configureStorage
  ignore_errors: yes
  when:
  - listening|success
